# **The Datasaurus Dozen**

```{r load_data_and_packages, message = FALSE}
library(tidyverse)
library(here)
library(gganimate)
#library(gifski)
library(magick)

datasaurus <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-10-13/datasaurus.csv')
```

```{r get statistics, message = FALSE}
stats <- datasaurus %>%
  group_by(dataset) %>% 
  summarize(
    mean_x    = round(mean(x),3),
    mean_y    = round(mean(y),3),
    std_dev_x = round(sd(x),3),
    std_dev_y = round(sd(y),3),
    corr_x_y  = round(cor(x, y),3)) %>% 
  ungroup()

datasaurus <- datasaurus %>% 
  left_join(stats)
```

```{r general settings}
theme_edges <- theme(axis.title = element_blank(),
                     axis.ticks = element_blank(),
                     axis.text = element_blank(),
                     axis.line = element_blank(),
                     plot.margin = unit(c(0, 0, 0, 0), "null"))

animation <- transition_states(dataset, 4, 1)


```

```{r prepare plots}
main_plot <- ggplot(datasaurus, aes(x=x, y=y))+
  geom_point(colour = ifelse(datasaurus$dataset == "dino", "darkgreen", "black"))+
  theme_classic() +
  theme(axis.ticks = element_blank(),
        axis.title = element_blank(),
        axis.text = element_text(size = 12),
        plot.margin = unit(c(0, 0, 0, 0), "null")) +
  geom_text(aes(x = 60, y = 136, label = paste("mean (x):", mean_x), hjust = 0), nudge_x = 15, nudge_y = -45) +
  geom_text(aes(x = 60, y = 132, label = paste("mean (y):", mean_y), hjust = 0), nudge_x = 15, nudge_y = -45) +
  geom_text(aes(x = 60, y = 128, label = paste("SD (x):", std_dev_x), hjust = 0), nudge_x = 15, nudge_y = -45) +
  geom_text(aes(x = 60, y = 124, label = paste("SD (y):", std_dev_y), hjust = 0), nudge_x = 15, nudge_y = -45) +
  geom_text(aes(x = 60, y = 120, label = paste("correlation", corr_x_y), hjust = 0), nudge_x = 15, nudge_y = -45) +
  animation + enter_fade() + exit_shrink() + ease_aes('sine-in-out') 

x_density <- ggplot(datasaurus, aes(x = x)) +
  geom_density(colour = "#FFFFFF", fill = "#3E9B00", alpha = 0.5) +
  theme_classic() +
  theme_edges +
  theme(panel.background = element_rect(fill = "transparent", colour = NA),  
        plot.background = element_rect(fill = "transparent", colour = NA),
        plot.title = element_text(size = 15),
        plot.subtitle = element_text(size = 13)) +
  animation + enter_fade() + exit_shrink() + ease_aes('sine-in-out') 

x_boxplot <- ggplot(datasaurus, aes(x = x)) +
  geom_boxplot(fill = "#3E9B00") +
  theme_classic() +
  theme_edges +
  animation + enter_fade() + exit_shrink() + ease_aes('sine-in-out')
  
y_density <- ggplot(datasaurus, aes(y = y)) +
  geom_density(colour = "#FFFFFF", fill = "#3E9B00", alpha = 0.5) +
  theme_classic() +
  theme_edges +
  theme(panel.background = element_rect(fill = "transparent", colour = NA),  
        plot.background = element_rect(fill = "transparent", colour = NA)) +
  animation + enter_fade() + exit_shrink() + ease_aes('sine-in-out')

y_boxplot <- ggplot(datasaurus, aes(y =y)) +
  geom_boxplot(fill = "#3E9B00") +
  theme_classic() +
  theme_edges +
  animation + enter_fade() + exit_shrink() + ease_aes('sine-in-out')


```

```{r animate image_read}
m_gif <- animate(main_plot, width = 240*1.5, height = 240*1.5)
xd_gif <- animate(x_density, width = 240*1.5, height = 120*1.5)
xb_gif <- animate(x_boxplot, width = 240*1.5, height = 35*1.5)
yd_gif <- animate(y_density, width = 100*1.5, height = 240*1.5)
yb_gif <- animate(y_boxplot, width = 35*1.5, height = 240*1.5)

m <- image_read(m_gif)
xd <- image_read(xd_gif)
xb <- image_read(xb_gif)
yb <- image_read(yb_gif)
yd <- image_read(yd_gif)
```

```{r put it all together, echo = FALSE}
combined  <- image_append(c(m[1],yb[1], yd[1]), stack = FALSE)
new_gif <- image_append(c(xd[1], xb[1], combined), stack = TRUE)

for(i in 2:100){
  combined <- image_append(c(m[i],yb[i], yd[i]), stack = FALSE)
  all_combined <- image_append(c(xd[i], xb[i], combined), stack = TRUE) %>% 
    image_annotate("These data sets have roughly the same summary statistics", font = 'Helvetica', size = 20, weight = 700) %>% 
    image_annotate("Visualize your data. Who knows what they hide!", font = "Helvetica", size = 18, weight = 600, location = "+0+25") #%>% 
    # image_annotate("Data source: Francis Anscombe, Alberto Cairo, Justin Matejka & George Fitzmaurice. Graphic: Louise Martens",
    #                size = 10, gravity = "southeast", location = "+0+20")
    # 
  new_gif <- c(new_gif, all_combined)
}

new_gif
```
